# Build configuration for code generation
targets:
  $default:
    builders:
      freezed:
        enabled: true
        options:
          # Generate copyWith methods
          copyWith: true
          # Generate == and hashCode
          equal: true
          # Generate toString
          to_string: true
      
      json_serializable:
        enabled: true
        options:
          # Create factory constructors
          create_factory: true
          # Create toJson methods
          create_to_json: true
          # Handle null values
          explicit_to_json: true
          # Use field rename
          field_rename: snake
          # Check required fields
          checked: true
          # Generate nullable fields
          any_map: false

