name: flutter_shopscript
description: A comprehensive Flutter plugin for ShopScript e-commerce platform integration with authentication, cart management, product catalog, orders, and offline support
version: 1.0.0
homepage: https://github.com/nativemind/flutter_shopscript
repository: https://github.com/nativemind/flutter_shopscript
issue_tracker: https://github.com/nativemind/flutter_shopscript/issues
documentation: https://github.com/nativemind/flutter_shopscript/wiki
topics:
  - shopscript
  - ecommerce
  - flutter
  - dart
  - api

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # Modern Platform Interface (Dart 3+ base classes)
  plugin_platform_interface: ^2.1.8
  
  # HTTP Client & API Generation
  dio: ^5.8.0
  http: ^1.1.0
  retrofit: ^4.0.1
  
  # State Management
  riverpod: ^3.0.0
  flutter_riverpod: ^3.0.0
  provider: ^6.1.5
  
  # JSON Serialization & Immutable Models
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  equatable: ^2.0.5
  
  # Modern Local Storage
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.15
  shared_preferences: ^2.2.2
  
  # Image Caching & Performance
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1
  visibility_detector: ^0.4.0+2
  
  # Network & Connectivity
  connectivity_plus: ^7.0.0
  
  # Device Information
  device_info_plus: ^12.1.0
  
  # Security & Authentication
  crypto: ^3.0.2
  flutter_secure_storage: ^9.2.2
  
  # Logging & Monitoring
  logger: ^2.6.2
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  intl_utils: ^2.8.0
  
  # Offline Support
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # Path operations
  path: ^1.8.3
  
  # File operations
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.5
  
  # Testing
  mockito: ^5.4.4
  json_serializable: ^6.9.0
  drift_dev: ^2.10.1
  freezed: ^3.2.3
  retrofit_generator: ^10.0.6
  
  # Testing & Quality
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0
  mocktail: ^1.0.4
  test: ^1.24.8
  integration_test:
    sdk: flutter
  
  # Test Coverage & Performance
  coverage: ^1.15.0

flutter:
  # This section identifies this package as a Flutter plugin
  plugin:
    platforms:
      android:
        package: com.nativemind.flutter.shopscript.flutter_shopscript
        pluginClass: FlutterShopScriptPlugin
      ios:
        pluginClass: FlutterShopScriptPlugin
      linux:
        pluginClass: FlutterShopScriptPlugin
      macos:
        pluginClass: FlutterShopScriptPlugin
      windows:
        pluginClass: FlutterShopScriptPlugin
      web:
        pluginClass: FlutterShopScriptPlugin
        fileName: flutter_shopscript_web.dart
